import { readFileSync } from "fs";
import { join } from "path";
import {
  PrioritizeRequestSchema,
  PrioritizeResponseSchema,
} from "@/lib/schemas";

export const runtime = "nodejs";

// Read function URL from amplify_outputs.json (generated by Amplify Gen 2 backend deploy)
// Falls back to PRIORITIZE_FUNCTION_URL env var for local development
let amplifyOutputs: { custom?: { prioritizeFunctionUrl?: string } } = {};
try {
  const outputsPath = join(process.cwd(), "amplify_outputs.json");
  const content = readFileSync(outputsPath, "utf-8");
  amplifyOutputs = JSON.parse(content);
} catch {
  // amplify_outputs.json not found — using env var fallback
}

const FUNCTION_URL =
  process.env.PRIORITIZE_FUNCTION_URL ||
  amplifyOutputs?.custom?.prioritizeFunctionUrl;

export async function POST(request: Request) {
  // --- Parse request body ---
  let body: unknown;
  try {
    body = await request.json();
  } catch (err) {
    console.error("[prioritize] Malformed request JSON", {
      message: err instanceof Error ? err.message : "unknown parse error",
    });
    return Response.json(
      { error: "Invalid JSON in request body." },
      { status: 400 }
    );
  }

  // --- Validate request with Zod ---
  const parsed = PrioritizeRequestSchema.safeParse(body);
  if (!parsed.success) {
    console.error("[prioritize] Zod request validation failed", {
      issues: parsed.error.issues.map((i) => ({
        path: i.path,
        code: i.code,
        message: i.message,
      })),
    });
    return Response.json(
      { error: parsed.error.issues[0]?.message || "Invalid request" },
      { status: 400 }
    );
  }

  const { tasks, availableTimeHours } = parsed.data;

  // --- Check function URL configuration ---
  if (!FUNCTION_URL) {
    console.error("[prioritize] PRIORITIZE_FUNCTION_URL not configured. Neither env var nor amplify_outputs.json custom.prioritizeFunctionUrl found.");
    return Response.json(
      {
        error:
          "The prioritization service is not configured. Please contact support.",
      },
      { status: 500 }
    );
  }

  // --- Pre-invocation diagnostic log (safe: no user text) ---
  console.error("[prioritize] Invoking prioritize function", {
    functionUrl: FUNCTION_URL.replace(/https?:\/\/[^/]+/, "***"),
    taskCount: tasks.length,
    availableTime: availableTimeHours,
  });

  // --- Invoke Lambda function URL ---
  let functionResponse: Response;
  try {
    functionResponse = await fetch(FUNCTION_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tasks, availableTimeHours }),
    });
  } catch (err) {
    console.error("[prioritize] Failed to invoke function", {
      message: err instanceof Error ? err.message : "unknown error",
    });
    return Response.json(
      {
        error:
          "The prioritization service is temporarily unavailable. Please try again.",
      },
      { status: 502 }
    );
  }

  if (!functionResponse.ok) {
    console.error("[prioritize] Function returned error status", {
      status: functionResponse.status,
    });
    return Response.json(
      {
        error:
          "The prioritization service is temporarily unavailable. Please try again.",
      },
      { status: 502 }
    );
  }

  // --- Parse function response ---
  let result: {
    success: boolean;
    responseText?: string;
    error?: { name: string; message: string };
  };
  try {
    result = await functionResponse.json();
  } catch (err) {
    console.error("[prioritize] Failed to parse function response", {
      message: err instanceof Error ? err.message : "unknown parse error",
    });
    return Response.json(
      {
        error:
          "The AI returned an unexpected response format. Please try again.",
      },
      { status: 502 }
    );
  }

  if (!result.success || !result.responseText) {
    console.error("[prioritize] Function reported failure", {
      errorName: result.error?.name,
      errorMessage: result.error?.message,
    });

    // Map known AWS errors to appropriate status codes
    const errorName = result.error?.name || "";
    if (
      [
        "AccessDeniedException",
        "ResourceNotFoundException",
        "ValidationException",
        "CredentialsProviderError",
      ].includes(errorName)
    ) {
      return Response.json(
        {
          error:
            "The prioritization service is temporarily unavailable. Please try again.",
        },
        { status: 502 }
      );
    }

    return Response.json(
      {
        error:
          "The prioritization service encountered an unexpected error. Please try again later.",
      },
      { status: 500 }
    );
  }

  // --- Parse JSON from Bedrock response ---
  // Strip markdown code fences if present (Bedrock sometimes wraps JSON in ```json ... ```)
  let responseText = result.responseText;
  const codeFenceMatch = responseText.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?\s*```$/);
  if (codeFenceMatch) {
    responseText = codeFenceMatch[1];
  }

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(responseText);
  } catch (err) {
    console.error("[prioritize] Failed to parse Bedrock response as JSON", {
      message: err instanceof Error ? err.message : "unknown parse error",
    });
    return Response.json(
      {
        error:
          "The AI returned an unexpected response format. Please try again.",
      },
      { status: 502 }
    );
  }

  // --- Validate response with Zod ---
  const validated = PrioritizeResponseSchema.safeParse(parsedJson);
  if (!validated.success) {
    console.error("[prioritize] Zod response validation failed", {
      issues: validated.error.issues.map((i) => ({
        path: i.path,
        code: i.code,
        message: i.message,
      })),
    });
    return Response.json(
      {
        error:
          "The AI returned an unexpected response format. Please try again.",
      },
      { status: 502 }
    );
  }

  return Response.json(validated.data);
}
